name: Flutter Build & Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated to latest version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0  # Specify a valid Flutter version
          channel: stable

      - name: Install Dependencies
        run: flutter pub get  # Ensures all dependencies are installed

      - name: Verify Flutter Installation
        run: flutter doctor  # Debugging step to check Flutter setup

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
